name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Mask multiline env
        run: |
          while read -r line;
          do
            echo "::add-mask::${line}"
          done <<< "${{ secrets.HIDE_THIS }}"
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build dependencies
        run: bun run build:deps
      - name: Run tests
        run: bun run test
